name: Unit tests

on:
   push:
      branches: [ "master" ]
   pull_request:
      branches: [ "master" ]

env:
   CARGO_TERM_COLOR: always

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repo
        uses: actions/checkout@main

      - name: Install latest nightly
        uses: actions-rs/toolchain@master
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy

      - name: Run tests
        run: cargo test
