name: Rust

on:
   push:
      branches: [ "master" ]
   pull_request:
      branches: [ "master" ]

env:
   CARGO_TERM_COLOR: always

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install latest nightly
        uses: actions-rs/toolchain@main
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy

      - name: Build
        run: cargo build

      - name: Run tests
        run: cargo test

      - name: Run benchmarks
        run: cargo bench
